import { ArrowRight, Check } from 'lucide-react'

import { CapabilityCard } from '@/components/site/capability-card'
import { getCapabilityMedia } from '@/components/site/capability-media'
import { ColorMatchingStory } from '@/components/site/color-matching-story'
import { Button, ButtonLink } from '@/components/ui/button'
import { Container } from '@/components/ui/container'
import type { Locale } from '@/i18n/locales'

const text = {
  en: { process: 'From artwork to a production-ready patch.', processLead: 'A focused workflow that resolves construction risks before repeat production.', steps: ['Artwork review', 'Structure & attachment proposal', 'Color matching', 'Sampling & confirmation', 'Controlled production'], capabilities: 'Small and focused. Built to solve detailed patch work.', about: 'Manufacturing knowledge with export-ready communication.', contact: 'Bring us the product, substrate, and use environment.', pending: 'Direct email, telephone, and detailed addresses are awaiting approved company details.', rfq: 'Brief your custom patch.', draft: 'Front-end preview only — backend connection follows in the inquiry phase.', legal: 'Draft for company review before publication.', privacy: 'Privacy notice', terms: 'Website terms', submit: 'Save inquiry draft', fields: ['Name', 'Company', 'Work email', 'Target market', 'Product interest', 'Application', 'Estimated quantity', 'Project details'] },
  ja: { process: 'デザインから量産可能なパッチへ。', processLead: '量産前に構造上のリスクを整理する、明確な工程です。', steps: ['デザイン確認', '構造・取り付け提案', '色合わせ', 'サンプル確認', '管理された量産'], capabilities: '小規模で専門的。細かなパッチ開発に集中。', about: '製造知識と輸出対応のコミュニケーション。', contact: '製品、基材、使用環境をお知らせください。', pending: 'メール、電話、詳細住所は会社承認情報の提供待ちです。', rfq: 'カスタムパッチの要件を共有。', draft: 'フロントエンドのプレビューです。問い合わせバックエンドは次段階で接続します。', legal: '公開前の会社確認用ドラフトです。', privacy: 'プライバシー通知', terms: 'サイト利用規約', submit: '問い合わせ下書きを保存', fields: ['氏名', '会社名', '業務用メール', '対象市場', '製品', '用途', '予定数量', 'プロジェクト詳細'] },
  'zh-CN': { process: '从设计稿到可量产的橡胶标牌。', processLead: '在重复生产前解决结构风险的清晰流程。', steps: ['设计稿审核', '结构与安装建议', '自动辅助调色', '打样确认', '受控量产'], capabilities: '小而精，专注解决细节型橡胶标牌项目。', about: '制造经验与面向出口的沟通能力。', contact: '请告诉我们产品、基材和使用环境。', pending: '企业邮箱、电话和详细地址正在等待公司批准资料。', rfq: '说明您的橡胶标牌需求。', draft: '当前为前端预览，询盘后端将在下一阶段连接。', legal: '当前为企业发布前审核草稿。', privacy: '隐私说明', terms: '网站条款', submit: '保存询盘草稿', fields: ['姓名', '公司', '工作邮箱', '目标市场', '产品意向', '应用场景', '预计数量', '项目详情'] },
} as const

function PageHero({ eyebrow, title, lead }: { eyebrow: string; title: string; lead?: string }) { return <section className="support-hero"><Container><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{lead ? <p className="page-lead">{lead}</p> : null}</Container></section> }

export function ProcessPage({ locale }: { locale: Locale }) { const t = text[locale]; return <main id="main-content"><PageHero eyebrow="WIZ / 01—05" title={t.process} lead={t.processLead}/><section className="content-section"><Container><ol className="process-list">{t.steps.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, '0')}</span><h2>{step}</h2><Check aria-hidden="true"/></li>)}</ol></Container></section><ColorMatchingStory/></main> }

export function CapabilitiesPage({ locale }: { locale: Locale }) { const t = text[locale]; return <main id="main-content"><PageHero eyebrow="Capabilities" title={t.capabilities}/><section id="capabilities" className="content-section"><Container className="capability-cards">{getCapabilityMedia(locale).map((capability) => <CapabilityCard capability={capability} key={capability.id}/>)}</Container></section></main> }

export function AboutPage({ locale }: { locale: Locale }) { const t = text[locale]; return <main id="main-content"><PageHero eyebrow="WIZ Electronic Gift Co., Limited" title={t.about}/><section className="content-section"><Container className="editorial-grid"><p className="eyebrow">Hong Kong · Dongguan</p><div><h2>{locale === 'zh-CN' ? '香港公司与自有内地工厂协同。' : locale === 'ja' ? '香港法人と自社の中国工場が連携。' : 'A Hong Kong company working with its owned mainland factory.'}</h2><p>{locale === 'zh-CN' ? '我们以八年以上相关经验，为品牌和制造客户提供橡胶标牌开发支持。公司规模保持精干，让沟通更直接、项目判断更贴近生产。' : locale === 'ja' ? '8年以上の関連経験を基に、ブランドと製造企業のラバーパッチ開発を支援します。小規模で専門的な体制により、直接的な対話と製造に近い判断を重視します。' : 'With more than eight years of related experience, WIZ supports rubber patch development for brands and manufacturers. A deliberately focused team keeps communication direct and decisions close to production.'}</p></div></Container></section></main> }

export function ContactPage({ locale }: { locale: Locale }) { const t = text[locale]; return <main id="main-content"><PageHero eyebrow="Contact" title={t.contact}/><section className="content-section"><Container className="contact-panel"><div><p className="eyebrow">Company details</p><p>{t.pending}</p></div><ButtonLink href={`/${locale}/rfq`}>{locale === 'zh-CN' ? '填写询盘需求' : locale === 'ja' ? '問い合わせを作成' : 'Build your inquiry'}<ArrowRight aria-hidden="true" size={16}/></ButtonLink></Container></section></main> }

export function LegalPage({ locale, kind }: { locale: Locale; kind: 'privacy' | 'terms' }) { const t = text[locale]; const title = t[kind]; return <main id="main-content"><PageHero eyebrow="Draft · Company review required" title={title} lead={t.legal}/><section className="content-section"><Container className="legal-copy"><h2>{locale === 'zh-CN' ? '发布前待确认' : locale === 'ja' ? '公開前の確認事項' : 'Before publication'}</h2><p>{locale === 'zh-CN' ? '需在后端、表单数据流、保留期限、服务商、联系方式和适用法律确定后，由企业审核正式文本。' : locale === 'ja' ? 'バックエンド、フォームのデータフロー、保存期間、サービス提供者、連絡先、準拠法の確定後に正式文面を企業が確認します。' : 'Final copy requires company review after the backend, form data flow, retention period, service providers, contact details, and governing law are confirmed.'}</p></Container></section></main> }

export function RfqPage({ locale, searchParams = {} }: { locale: Locale; searchParams?: Record<string, string | undefined> }) { const t = text[locale]; const names = ['name', 'company', 'email', 'market', 'product', 'application', 'quantity', 'details']; const autocomplete: Record<string, string> = { name: 'name', company: 'organization', email: 'email', market: 'country-name', product: 'off', application: 'off', quantity: 'off' }; return <main id="main-content"><PageHero eyebrow="RFQ / Project brief" title={t.rfq} lead={t.draft}/><section className="content-section"><Container><form className="rfq-form"><div className="rfq-form__grid">{names.map((name, index) => <label className={name === 'details' ? 'field field--wide' : 'field'} key={name}><span>{t.fields[index]}</span>{name === 'details' ? <textarea autoComplete="off" name="details" rows={6}/> : <input autoComplete={autocomplete[name]} defaultValue={searchParams[name] ?? ''} inputMode={name === 'quantity' ? 'numeric' : undefined} name={name} spellCheck={name === 'email' ? false : undefined} type={name === 'email' ? 'email' : name === 'quantity' ? 'number' : 'text'}/>}</label>)}</div><p className="form-status">{t.draft}</p><Button disabled type="button">{t.submit}</Button></form></Container></section></main> }
