-- 202608130001_catalog_editorial_fields.sql
-- NO-OP: all catalog editorial fields (tone, priority on base tables; surrogate id
-- PK + eyebrow/suitability/construction/visual_options/attachment_options/
-- artwork_guidance/buyer_problem/attachment_considerations/visual_direction on
-- translation tables) have been merged into 202608120001_core_schema.sql to
-- eliminate fragile multi-migration ALTER TABLE chains under Supabase CLI.
--
-- This file is kept as a placeholder so existing migration records remain valid.
-- It contains no DDL statements.
